# Generated by Django 5.1.3 on 2024-12-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_topics',
            field=models.ManyToManyField(blank=True, related_name='completed_profiles', to='myapp.subtopic'),
        ),
    ]
